Cool stuff

diff --git a/scripts/codediff b/scripts/codediff
--- a/scripts/codediff
+++ b/scripts/codediff
@@ -25,12 +25,25 @@ elif [ -f "$1" ] && [ -f "$2" ]; then
             nvim -d $local $remote
             ;;
     esac
+elif [ "`git rev-parse --show-toplevel`" ]; then
+    # We are in a git directory
+    if [ -d "$1" ]; then
+        git difftool --dir-diff $1
+    elif [ -f "$1" ]; then
+        git difftool $1
+    else
+        if [ ! -f "$file" ]; then
+            echo "Could not find '$1'"
+            sleep 5
+            exit 1
+        fi
+    fi
 else
     # Opening a file
     file="$1"
 
     if [ ! -f "$file" ]; then
-        echo "'$file' not found!"
+        echo "File '$file' not found!"
         sleep 5
         exit 1
     fi
